In [1]:
import torch
import torch.nn as nn
from torchinfo import summary

In [2]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)  # nn.Linear(number of input, number of output)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        output = self.linear(features)
        output = self.sigmoid(output)
        return output

In [3]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)   # model.forward(features) can be used too but PyTorch uses a magic function which automatically calls forward function


tensor([[0.4796],
        [0.4152],
        [0.4790],
        [0.4676],
        [0.3946],
        [0.4720],
        [0.4449],
        [0.4106],
        [0.4649],
        [0.4436]], grad_fn=<SigmoidBackward0>)

In [4]:
print(model.linear.weight)
print(model.linear.weight.shape)

Parameter containing:
tensor([[-0.4115,  0.0533, -0.0556,  0.3099,  0.0461]], requires_grad=True)
torch.Size([1, 5])


In [5]:
print(model.linear.bias)
print(model.linear.bias.shape)

Parameter containing:
tensor([-0.1282], requires_grad=True)
torch.Size([1])


In [7]:
summary(model, input_size= features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00