In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from torch.utils.data import Dataset, DataLoader

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(['id','Unnamed: 32'], axis=1, inplace=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

<font size="6" color='pink'>Data Splitting</font>

In [7]:
y = df['diagnosis']
df.drop('diagnosis', axis=1, inplace=True)
X = df

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
print(f'Length of X_train is {len(X_train)}')
print(f'Length of X_test is {len(X_test)}')
print(f'Length of y_train is {len(y_train)}')
print(f'Length of X_test is {len(y_test)}')

Length of X_train is 455
Length of X_test is 114
Length of y_train is 455
Length of X_test is 114


In [10]:
type(X_train)

pandas.core.frame.DataFrame

In [11]:
type(y_train)

pandas.core.series.Series

<font size="4" color='yellow'>Data Scaling</font>

In [12]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [13]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
type(X_train)

numpy.ndarray

<font size="4" color='yellow'>Label Encoding</font>

In [15]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

In [16]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

In [17]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

<font size="4" color='yellow'>Numpy to Tensors</font>

In [18]:
X_train = torch.from_numpy(X_train).float()
X_test = torch.from_numpy(X_test).float()
y_train = torch.from_numpy(y_train).float()
y_test = torch.from_numpy(y_test).float()

In [19]:
type(X_train)

torch.Tensor

In [20]:
type(y_train)

torch.Tensor

In [21]:
X_train.shape

torch.Size([455, 30])

In [22]:
X_train.dtype

torch.float32

In [23]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [32]:
train_dataset = CustomDataset(X_train, y_train)
test_dataset = CustomDataset(X_test, y_test)

In [33]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

<font size="6" color='pink'>Defining the Model</font>

In [25]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        output = self.linear(features)
        output = self.sigmoid(output)
        return output

<font size="4" color='yellow'>Important Parameters</font>

In [26]:
learning_rate = 0.1
epochs = 25

<font size="4" color='yellow'>Loss Function</font>

In [27]:
loss_function = nn.BCELoss()

<font size="4" color='yellow'>Training Pipeline</font>

In [34]:
model = Model(X_train.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)  # model.parameters contains weights and bias

# Define the Loop
for epoch in range(epochs):

    for batch_features, batch_labels in train_loader:
    # Forward Pass
        y_pred = model(batch_features)
        # Loss Calculate
        loss = loss_function(y_pred, batch_labels.view(-1,1))
    
        # Clear Gradients before Backward Pass
        optimizer.zero_grad()
        # Backward Pass
        loss.backward()
        # Parameters Update
        optimizer.step()

        print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.5736220479011536
Epoch: 1, Loss: 0.44172394275665283
Epoch: 1, Loss: 0.529033362865448
Epoch: 1, Loss: 0.39166414737701416
Epoch: 1, Loss: 0.35580578446388245
Epoch: 1, Loss: 0.2813699543476105
Epoch: 1, Loss: 0.28426843881607056
Epoch: 1, Loss: 0.29468417167663574
Epoch: 1, Loss: 0.29674845933914185
Epoch: 1, Loss: 0.254189670085907
Epoch: 1, Loss: 0.2259763777256012
Epoch: 1, Loss: 0.24689050018787384
Epoch: 1, Loss: 0.2629935145378113
Epoch: 1, Loss: 0.2550537884235382
Epoch: 1, Loss: 0.24510157108306885
Epoch: 2, Loss: 0.23566529154777527
Epoch: 2, Loss: 0.1478874832391739
Epoch: 2, Loss: 0.20385144650936127
Epoch: 2, Loss: 0.15062490105628967
Epoch: 2, Loss: 0.1888987123966217
Epoch: 2, Loss: 0.1587735265493393
Epoch: 2, Loss: 0.18800058960914612
Epoch: 2, Loss: 0.1955072283744812
Epoch: 2, Loss: 0.24107670783996582
Epoch: 2, Loss: 0.20269960165023804
Epoch: 2, Loss: 0.1844937801361084
Epoch: 2, Loss: 0.22584635019302368
Epoch: 2, Loss: 0.17551380395889282
Epoch:

In [29]:
model.linear.weight

Parameter containing:
tensor([[ 0.3019,  0.1907,  0.2969,  0.2371,  0.0793,  0.0149,  0.2645,  0.2563,
          0.1062,  0.0376,  0.0936,  0.1545,  0.2323,  0.1806, -0.1696, -0.0722,
          0.1106,  0.1056, -0.0746, -0.2278,  0.2031,  0.1066,  0.1868,  0.2991,
          0.2571,  0.2195,  0.0738,  0.2346,  0.0559,  0.1264]],
       requires_grad=True)

In [30]:
model.linear.bias

Parameter containing:
tensor([-0.2171], requires_grad=True)

In [36]:
model.eval()

Model(
  (linear): Linear(in_features=30, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

<font size="6" color='pink'>Evaluation</font>

In [39]:
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        y_pred = model.forward(batch_features)
        y_pred = (y_pred>0.5).float()
        accuracy = (y_pred == batch_labels).float().mean().item()
        accuracy_list.append(accuracy)

overall_accuracy = sum(accuracy_list)/len(accuracy_list)        
print(f'Accuracy is {overall_accuracy}%')

Accuracy is 0.537109375%
