In [65]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

2.6.0+cpu


<font size="4" color='yellow'>To check if GPU is available</font>

In [4]:
if torch.cuda.is_available():
    print('GPU is Available')
    print(torch.cuda.get_device_name(0))
else:
    print('GPU is Not Available. Using CPU')

GPU is Not Available. Using CPU


<font size="4" color='yellow'>Ways to Create Tensors</font>

In [5]:
a = torch.empty(2,3)

In [6]:
print(a)
print(type(a))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(2,3)

tensor([[0.4153, 0.5729, 0.5572],
        [0.2511, 0.0930, 0.4488]])

In [11]:
torch.rand(2,3)

tensor([[0.5645, 0.0301, 0.2451],
        [0.3472, 0.5647, 0.6621]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [27]:
# Manually Created Tensors
a = torch.tensor([[1,2,3],[4,5,6]])
print(a)
print(type(a))
print(a.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>
torch.Size([2, 3])


In [51]:
a.flatten()

tensor([1., 2., 3., 4., 5., 6.])

In [25]:
# Other tensor creating methods

# arange
print(f'Using arange: {torch.arange(1,10)}')

# linspace(linear space)
print(f'Using linspace: {torch.linspace(0,10,8)}')

# eye (Identity Matrix)
print(f'Using eye: {torch.eye(5)}')

# full
print(f'Using full: {torch.full((3,3),5)}')

Using arange: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Using linspace: tensor([ 0.0000,  1.4286,  2.8571,  4.2857,  5.7143,  7.1429,  8.5714, 10.0000])
Using eye: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full: tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [28]:
# if we want to create tensor of same size as given, we'll use _like
torch.empty_like(a)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
a.dtype

torch.int64

In [38]:
# change data type
a = a.to(torch.float32)

In [39]:
a.dtype

torch.float32

<font size="4" color='yellow'>Copying a Tensor</font>

In [42]:
arr1 = torch.tensor([[1,2,3],[4,5,6]])
arr1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [43]:
# using clone() we can create a copy of a tensor
arr2 = arr1.clone()
arr2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [46]:
arr1[0][0] = 0
arr1

tensor([[0, 2, 3],
        [4, 5, 6]])

In [47]:
arr2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Here, we have created a copy of arr1, so if we change any of them, then the other will not have any effect.

In [49]:
# to check their location
print(id(arr1))
print(id(arr2))

2119085601280
2119085599360


<font size="4" color='yellow'>Permute</font>

In [62]:
 # This function is used to rearrange the dimensions of a tensor.
arr = torch.rand(2,3,4)
print(arr)
print(arr.shape)

tensor([[[0.5277, 0.2472, 0.7909, 0.4235],
         [0.0169, 0.2209, 0.9535, 0.7064],
         [0.1629, 0.8902, 0.5163, 0.0359]],

        [[0.6476, 0.3430, 0.3182, 0.5261],
         [0.0447, 0.5123, 0.9051, 0.5989],
         [0.4450, 0.7278, 0.4563, 0.3389]]])
torch.Size([2, 3, 4])


In [64]:
permuted_arr = arr.permute(2,0,1)
permuted_arr
print(permuted_arr.shape)

torch.Size([4, 2, 3])


<font size="4" color='yellow'>Tensor to Numpy</font>

In [66]:
num_arr = arr.numpy()

In [67]:
print(num_arr)
print(type(num_arr))

[[[0.5276887  0.24718356 0.79088616 0.42348665]
  [0.01689917 0.22089463 0.95353633 0.70640296]
  [0.16287827 0.890198   0.5162713  0.03588456]]

 [[0.6476328  0.34302562 0.31824023 0.5260877 ]
  [0.04465872 0.512348   0.9050759  0.59885734]
  [0.44500393 0.7278287  0.45625782 0.3388673 ]]]
<class 'numpy.ndarray'>


<font size="4" color='yellow'>Numpy to Tensor</font>

In [68]:
arr = torch.from_numpy(num_arr)

In [69]:
print(arr)
print(type(arr))

tensor([[[0.5277, 0.2472, 0.7909, 0.4235],
         [0.0169, 0.2209, 0.9535, 0.7064],
         [0.1629, 0.8902, 0.5163, 0.0359]],

        [[0.6476, 0.3430, 0.3182, 0.5261],
         [0.0447, 0.5123, 0.9051, 0.5989],
         [0.4450, 0.7278, 0.4563, 0.3389]]])
<class 'torch.Tensor'>
