In [1]:
import torch
import numpy as np

<font size="4" color='yellow'>Scalar</font>

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

<font size="4" color='yellow'>Vector</font>

In [5]:
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

<font size="4" color='yellow'>Matrix</font>

In [8]:
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

<font size="4" color='yellow'>Tensor</font>

In [11]:
tensor1 = torch.tensor([[[1,1,1],[2,2,2],[3,3,3]]])
tensor1

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]])

In [12]:
tensor1.ndim

3

In [13]:
tensor1.shape

torch.Size([1, 3, 3])

In [14]:
tensor2 = torch.tensor([[[1,1,1],[2,2,2],[3,3,3]],
                       [[4,4,4],[5,5,5],[6,6,6]]])
tensor2

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]],

        [[4, 4, 4],
         [5, 5, 5],
         [6, 6, 6]]])

In [15]:
tensor2.ndim

3

In [16]:
tensor2.shape

torch.Size([2, 3, 3])

In [17]:
# dtype

In [18]:
float_tensor = torch.tensor([3,6,9], dtype=torch.float32)

In [19]:
print(float_tensor)
print(float_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [20]:
int_tensor = torch.tensor([2,4,8], dtype=torch.int64)

In [21]:
print(int_tensor)
print(int_tensor.dtype)

tensor([2, 4, 8])
torch.int64


In [22]:
float_tensor * int_tensor

tensor([ 6., 24., 72.])

In [23]:
int_tensor.device

device(type='cpu')

<font size="4" color='yellow'>Details about a Created Tensor</font>

In [24]:
arr = torch.rand(3,4)

In [25]:
print(arr)
print()
print(f"Datatype of Tensor: {arr.dtype}")
print(f"Shape of Tensor: {arr.shape}")
print(f"Device on which Tensor: {arr.device}")

tensor([[0.0608, 0.3364, 0.6700, 0.4950],
        [0.4542, 0.1746, 0.8516, 0.2357],
        [0.3200, 0.5434, 0.0816, 0.0872]])

Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device on which Tensor: cpu


<font size="4" color='yellow'>Manipulating Tensor</font>

In [26]:
arr1 = torch.tensor([1,2,3])

In [27]:
print(f"Addition: {torch.add(arr1,10)}")
print(f"Subtraction: {arr1 - 10}")
print(f"Multiplication: {torch.mul(arr1,10)}")
print(f"Division: {torch.div(arr1,10)}")
print(f"Modulus: {torch.remainder(arr1,10)}")

Addition: tensor([11, 12, 13])
Subtraction: tensor([-9, -8, -7])
Multiplication: tensor([10, 20, 30])
Division: tensor([0.1000, 0.2000, 0.3000])
Modulus: tensor([1, 2, 3])


In [28]:
# Element-wise multiplication
arr1 = torch.tensor([1,2,3])
arr2 = torch.tensor([1,2,3])

print(f'Element-wise Multiplication: {arr1 * arr2}')

Element-wise Multiplication: tensor([1, 4, 9])


In [29]:
# Matrix multiplication
arr1 = torch.tensor([1,2,3])
arr2 = torch.tensor([1,2,3])

print(f'Matrix Multiplication: {torch.matmul(arr1,arr2)}')

Matrix Multiplication: 14


In [30]:
tensor_arr = torch.arange(1, 10, dtype=torch.float32)
tensor_arr

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
tensor_arr.dtype

torch.float32

In [32]:
print(f'Min: {tensor_arr.min()}')
print(f'Max: {tensor_arr.max()}')
print(f'Sum: {tensor_arr.sum()}')
print(f'Mean: {tensor_arr.mean()}')

Min: 1.0
Max: 9.0
Sum: 45.0
Mean: 5.0


In [33]:
print(f'Position of Smallest Element: {tensor_arr.argmin()}')
print(f'Position of Largest Element: {tensor_arr.argmax()}')
print(f'Sorted Index: {tensor_arr.argsort()}')

Position of Smallest Element: 0
Position of Largest Element: 8
Sorted Index: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [34]:
arr = torch.rand(2,3)
arr,arr.shape

(tensor([[0.3235, 0.0825, 0.8544],
         [0.8280, 0.0028, 0.9934]]),
 torch.Size([2, 3]))

In [35]:
arr = arr.reshape(3,2)
arr, arr.shape

(tensor([[0.3235, 0.0825],
         [0.8544, 0.8280],
         [0.0028, 0.9934]]),
 torch.Size([3, 2]))

In [36]:
arr.flatten()

tensor([0.3235, 0.0825, 0.8544, 0.8280, 0.0028, 0.9934])

In [37]:
# after set unsqueeze 1, tensor becomes 2d

tensor = torch.tensor([1,2,3])
arr = tensor.unsqueeze(1)
arr, tensor.shape, arr.shape

(tensor([[1],
         [2],
         [3]]),
 torch.Size([3]),
 torch.Size([3, 1]))

In [38]:
x = arr.squeeze()
x

tensor([1, 2, 3])

In [39]:
# permute
arr = torch.rand(2,4,3)
arr, arr.shape

(tensor([[[0.9836, 0.1223, 0.1075],
          [0.7254, 0.8215, 0.5523],
          [0.5338, 0.4649, 0.9066],
          [0.2183, 0.7116, 0.1660]],
 
         [[0.8148, 0.6436, 0.4616],
          [0.6790, 0.1220, 0.8803],
          [0.9853, 0.8876, 0.8459],
          [0.1981, 0.6003, 0.5478]]]),
 torch.Size([2, 4, 3]))

In [40]:
permuted_arr = arr.permute(2,0,1)
permuted_arr, permuted_arr.shape

(tensor([[[0.9836, 0.7254, 0.5338, 0.2183],
          [0.8148, 0.6790, 0.9853, 0.1981]],
 
         [[0.1223, 0.8215, 0.4649, 0.7116],
          [0.6436, 0.1220, 0.8876, 0.6003]],
 
         [[0.1075, 0.5523, 0.9066, 0.1660],
          [0.4616, 0.8803, 0.8459, 0.5478]]]),
 torch.Size([3, 2, 4]))

<font size="4" color='yellow'>Indexing</font>

In [41]:
# Basic Indexing
arr = torch.arange(1,10)
print(arr)
print(arr[0]) # First Element
print(arr[4]) # Element at 4th position
print(arr[-1]) # Last Element

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(1)
tensor(5)
tensor(9)


In [42]:
# Indexing in 2d

arr = torch.rand(2,2)
print(arr)
print(arr[0][0])
print(arr[0][1])
print(arr[1][0])
print(arr[0][1])

tensor([[0.8932, 0.9052],
        [0.0300, 0.1493]])
tensor(0.8932)
tensor(0.9052)
tensor(0.0300)
tensor(0.9052)


In [43]:
# Indexing in 3d
# 3d = [batch, row, columns]

arr = torch.rand(2,2,2)
print(arr)
print(arr[0][0][0])
print(arr[1][0][0])
print(arr[0][:][:])
print()
print(arr[1][:][:])

tensor([[[0.1443, 0.9792],
         [0.9768, 0.1196]],

        [[0.8738, 0.3513],
         [0.4129, 0.6312]]])
tensor(0.1443)
tensor(0.8738)
tensor([[0.1443, 0.9792],
        [0.9768, 0.1196]])

tensor([[0.8738, 0.3513],
        [0.4129, 0.6312]])


<font size="4" color='yellow'>Tensor to Numpy</font>

In [44]:
tensors = torch.rand([2,2])

In [45]:
num_arr = tensors.numpy()

In [46]:
print(num_arr)
print(type(num_arr))

[[0.6483172  0.09843659]
 [0.45395392 0.15300101]]
<class 'numpy.ndarray'>


<font size="4" color='yellow'>Numpy to Tensor</font>

In [47]:
tensors = torch.from_numpy(num_arr)

In [48]:
print(tensors)
print(type(tensors))

tensor([[0.6483, 0.0984],
        [0.4540, 0.1530]])
<class 'torch.Tensor'>


<font size="4" color='yellow'>Reproducibility</font>

In [49]:
# It will give different result

tensor1 = torch.rand(2,2)
tensor2 = torch.rand(2,2)

print(tensor1)
print(tensor2)
print(tensor1 == tensor2)

tensor([[0.9892, 0.7898],
        [0.7581, 0.5585]])
tensor([[0.1701, 0.4731],
        [0.1601, 0.4961]])
tensor([[False, False],
        [False, False]])


In [50]:
# # It will give same result

# torch.manual_seed(42)
# tensor1 = torch.rand(2,2)

# torch.manual_seed(42)
# tensor2 = torch.rand(2,2)

# print(tensor1)
# print(tensor2)
# print(tensor1 == tensor2)

In [56]:
tensor1 = torch.rand(2,2)
print(tensor1)

tensor([[0.1315, 0.2505],
        [0.6915, 0.6674]])


In [59]:
tensor2 = tensor1.clone()
print(tensor2)

tensor([[0.1315, 0.2505],
        [0.6915, 0.6674]])
